name: 'Send notification'
description: 'Send notification'
inputs:
  webhook:
    description: 'url of api to call'
    required: false
  message:
    description: 'message details'
    required: false
outputs:
  id:
    description: 'Notification Id'
runs:
  using: 'node20'
  main: './src/notify.js'