name: quality workflow
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - uses: ./.github/actions/nest-ci-action
        with:
          package_manager: "npm"

      - name: Send notification
        id: send-notification
        uses: ./
        with:
          webhook: ${{ secrets.NOTIFY_WEBHOOK }}
          message: ${{ github.event.inputs.message }}
          channel: ${{ github.event.inputs.message }}

      - name: Display send notification output
        run: echo "${{steps.send-notification.outputs.id}}"

      - uses: alaleau/my-composites-actions/actions/cleanup-cache-action@main
        with:
          package_manager: "npm"


