name: quality workflow
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Send notification
        id: send-notification
        uses: ./
        with:
          webhook: ${{ secrets.NOTIFY_WEBHOOK }}
          message: "My message"

      - name: Display send notification output
        run: echo "${{steps.send-notification.outputs.id}}"

      - uses: alaleau/my-composites-actions/actions/cleanup-cache-action@main
        with:
          package_manager: "npm"

